import java.awt.event.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.io.*;
/**
 *
 * @author HimanshuGaur
 */
public class gaurdside extends javax.swing.JFrame {

    Connection con,con1;
    ResultSet rs1,rs2;
    Statement stmt,stmt1;
    String barcode_no,days;
    int flag,sNo=0,pos=0;
    Calendar c ;
    File image;
    Object o;
	int cc=0;
    //StringBuffer first_name= new StringBuffer();
    //StringBuffer last_name= new StringBuffer();
    /**
     * Creates new form gaurdside
     */
    public gaurdside() {
        initComponents();
		jTextField1.requestFocus();
       try
       {
       
        //database();
       }
       catch(Exception e)
       {
       	System.out.println("initialization error");
       	System.exit(1);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("                            JECRC  Exit System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); 

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		
	 jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseListener()
        {
        	public void mouseClicked(java.awt.event.MouseEvent x)
        	{
        		jtextMouseClicked(x);
        	}
        	public void mouseEntered(java.awt.event.MouseEvent x)
        	{
        		//jtextMouseClicked(x);
        		int x1;
        		x1=1;
        	}
        	public void mouseExited(java.awt.event.MouseEvent x)
        	{
        		//jtextMouseClicked(x);
        		int x2;
        		x2=1;
        	}
        	public void mousePressed(java.awt.event.MouseEvent x)
        	{
        		int x3;
        		x3=1;
        		//jtextMouseClicked(x);
        	}
        	public void mouseReleased(java.awt.event.MouseEvent x)
        	{
        		int x4;
        		x4=1;
        		//jtextMouseClicked(x);
        	}
        	
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Bar Code no");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("First Name");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Branch");

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shut.png"))); 
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Out time");

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.jpg"))); 
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Enter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Login");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        jMenuItem2.setText("Admin Login");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(426, 426, 426))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		setVisible(false);
		System.exit(1);
	   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void database(String barcode) throws SQLException,ClassNotFoundException
	{
	
		Class.forName("com.mysql.jdbc.Driver");
		con=DriverManager.getConnection("jdbc:mysql://localhost:3306/entrysystem","root","admin");
	//	con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/entrysystem","root","roota");
		stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
      //  stmt1=con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
		rs1 = stmt.executeQuery("select * from student where barCodeNo = '"+barcode+"'");
       // rs2 = stmt1.executeQuery("select sNo , barCodeNo , day , date , outTime from timeupdate");
        //System.out.println(rs1);
   //rs2 = stmt.executeQuery("select barCodeNo , day , date , outTime from timeupdate");
	}
	private void database1() throws SQLException,ClassNotFoundException
	{
	
		Class.forName("com.mysql.jdbc.Driver");
		//con=DriverManager.getConnection("jdbc:mysql://localhost:3306/entrysystem","root","roota");
		con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/entrysystem","root","admin");
	//	stmt=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        stmt1=con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
	//	rs1 = stmt.executeQuery("select barCodeNo , name , mobileNo , fatherName , year , section , branch , photo from student");
        rs2 = stmt1.executeQuery("select * from timeupdate");
        //System.out.println(rs1);
                //rs2 = stmt.executeQuery("select barCodeNo , day , date , outTime from timeupdate");
	}
	private void jtextMouseClicked(java.awt.event.MouseEvent e)
	{
		jTextField1.setText(null);
	}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            if(flag==1)
            {
                
                    try {
                        try {
                            try {
                                database1();
                                go();
                            } catch (SQLException ex) {
                                Logger.getLogger(gaurdside.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(gaurdside.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            rs2.moveToInsertRow();
                            
                        } catch (SQLException ex) {
                            Logger.getLogger(gaurdside.class.getName()).log(Level.SEVERE, null, ex);
                        }
						c= Calendar.getInstance();
                        if(c.get(Calendar.DAY_OF_WEEK)==1)
                            rs2.updateString("day","Sunday");
                        else if(c.get(Calendar.DAY_OF_WEEK)==2)
                            rs2.updateString("day","Monday");
                        else if(c.get(Calendar.DAY_OF_WEEK)==3)
                            rs2.updateString("day","Tuesday");
                        else if(c.get(Calendar.DAY_OF_WEEK)==4)
                            rs2.updateString("day","Wednesday");
                        else if(c.get(Calendar.DAY_OF_WEEK)==5)
                            rs2.updateString("day","Thursday");
                        else if(c.get(Calendar.DAY_OF_WEEK)==6)
                            rs2.updateString("day","Friday");
                        else if(c.get(Calendar.DAY_OF_WEEK)==7)
                            rs2.updateString("day","Saturday");
                        rs2.updateInt("sNo",(sNo+1));
                        rs2.updateString("barCodeNo",jTextField3.getText());
						int mon=c.get(Calendar.MONTH)+1;
                        rs2.updateString("date",c.get(Calendar.DATE)+"-"+mon+"-"+c.get(Calendar.YEAR));
                        rs2.updateString("outTime",c.get(Calendar.HOUR)+":"+c.get(Calendar.MINUTE)+":"+c.get(Calendar.SECOND));
                        rs2.insertRow();
                        rs2.close();
                        stmt1.close();
                        con1.close();
                        image = new java.io.File("D:\\temp.png");
                        image.delete();
                        jTextField1.setText(null);
                        //javax.swing.ImageIcon icon = new javax.swing.ImageIcon(null);
                        //jLabel8.setIcon(null);
						jTextField1.requestFocus();
                    }
                     catch (SQLException ex) {
                        Logger.getLogger(gaurdside.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"    Scanning Error!" , "FAILURE!!", JOptionPane.PLAIN_MESSAGE);
				jTextField1.requestFocus();
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void  image() 
    {
        try
        {
            image = new File("D:/temp.png");
            FileOutputStream fos = new FileOutputStream(image);

            byte[] buffer = new byte[1];
            InputStream is = rs1.getBinaryStream("photo");
            while (is.read(buffer) > 0) {
                fos.write(buffer);
            }
            fos.close();
           // o = image;
      }
      catch(Exception e)
      {
      	e.printStackTrace();
      }
    }
    
    private void go() throws SQLException, ClassNotFoundException
    {
        rs2.beforeFirst();
        while(rs2.next())
        {
            sNo=rs2.getInt("sNo");
        }
        
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       // jTextField1.setText(null);
        String st = jTextField1.getText();
       // System.out.println(st);
        String first_name="";
        String last_name="";
        if(st.equals(""))
                {
                    JOptionPane.showMessageDialog(rootPane," Empty barcode not allowed!" , "FAILURE!!", JOptionPane.PLAIN_MESSAGE);
                    // TODO add your handling code here:
                    flag=0;
                    jTextField5.setText("");
                    jTextField4.setText("");
                    jTextField3.setText("");
                    jTextField2.setText("");
                    jTextField6.setText("");
                    jLabel8.setIcon(null);
                }
        else
        {
            try {
            	String sss=jTextField1.getText();
                if(sss.length()!=6)
	        	{
	        		JOptionPane.showMessageDialog(rootPane,"   Not a valid barcode!" , "FAILURE!!", JOptionPane.PLAIN_MESSAGE);
	        		//System.out.print("wrong value");
	        	//	jTextField1.setText(null);
	        		jTextField1.setText("");
                    jTextField5.setText("");
                    jTextField4.setText("");
                    jTextField3.setText("");
                    jTextField2.setText("");
                    jTextField6.setText("");
                    jLabel8.setIcon(null);
	        	//	pos=0;
				
	        	//	System.out.println("posAT "+pos);
	        	//	return;
	        	}
		        else if(sss.length()==6)
		       	{
			       	//System.out.println(textField.getText());
			       	int counter=0;
			       	pos=sss.length();
			       	System.out.println("pos ="+pos);
			       //extField.setText("");
			       database(sss);
			       rs1.beforeFirst();
			       while(rs1.next())
			       {
			       	counter++;
			       }
			       System.out.print(rs1);
			       if(counter==0)
	                {
	                		JOptionPane.showMessageDialog(rootPane,"   Not a valid barcode!" , "FAILURE!!", JOptionPane.PLAIN_MESSAGE);
		                  //  jTextField1.setText("");
		                    jTextField1.setText("");
		                    jTextField5.setText("");
		                    jTextField4.setText("");
		                    jTextField3.setText("");
		                    jTextField2.setText("");
		                    jTextField6.setText("");
		                    jLabel8.setIcon(null);
							
		                    return;	
	                }
	                else if(counter==1)
	                {
	                	rs1.beforeFirst();
	                	rs1.next();
	                	image();
	                    jLabel8.setIcon(null);
	                    image =(java.io.File)o;
	                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon("D:/temp.png");
	                    jLabel8.setHorizontalAlignment(javax.swing.JLabel.CENTER);
	                    icon.getImage().flush();
	                    jLabel8.setIcon(icon);
	                    String name = rs1.getString("name");
                        int i=0;
                        while(name.charAt(i)!=' ')
                        {
                            first_name=first_name+ name.charAt(i);
                            i++;
                        }
                        i++;
                        while(i<name.length())
                        {
                            last_name=last_name + name.charAt(i);
                            i++;
                        }
                        jTextField2.setText(last_name);
                        jTextField5.setText(first_name);
                        jTextField4.setText(rs1.getString("branch"));
                        jTextField3.setText(rs1.getString("barCodeNo"));
						c= Calendar.getInstance();
                        jTextField6.setText(c.get(Calendar.HOUR)+":"+c.get(Calendar.MINUTE)+":"+c.get(Calendar.SECOND));
                        
                        flag=1;
                      rs1.close();
                      stmt.close();
                      con.close();
					  
					  jButton3.requestFocus();
	                    
	                }
				       	
		       	}
              
            } catch (Exception ex) {
                Logger.getLogger(gaurdside.class.getName()).log(Level.SEVERE, null, ex);
            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
     
    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                    // TODO add your handling code here:
                    jTextField1.setText("");
                    jTextField5.setText("");
                    jTextField4.setText("");
                    jTextField3.setText("");
                    jTextField2.setText("");
                    jTextField6.setText("");
                    jLabel8.setIcon(null);
					jTextField1.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gaurdside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gaurdside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gaurdside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gaurdside.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gaurdside().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
